# Generated by Django 4.2.11 on 2026-03-14 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(default='Mumbai', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clinics/')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('distance_km', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('tags', models.JSONField(default=list)),
                ('opening_time', models.TimeField(default='09:00')),
                ('closing_time', models.TimeField(default='21:00')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clinics',
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
