# Generated by Django 6.0.3 on 2026-04-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('timeslots', '0001_initial'),
        ('users', '0004_add_doctor_clinic_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Which clinic this schedule applies to. Null = legacy support.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Which clinic this slot is at.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='clinics.clinic'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'clinic', 'weekday', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('doctor', 'clinic', 'date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['doctor', 'clinic', 'date'], name='time_slots_doctor__8d896e_idx'),
        ),
    ]
