# Generated by Django 6.0.3 on 2026-04-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Which clinic the appointment is at.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinics.clinic'),
        ),
    ]
