# Generated by Django 6.0.3 on 2026-03-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctorprofile_clinic_doctorprofile_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_token',
            field=models.CharField(blank=True, help_text='Expo push notification token', max_length=200, null=True),
        ),
    ]
