# Generated by Django 6.0.3 on 2026-04-02 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('users', '0003_user_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_doctors', to='clinics.clinic'),
        ),
        migrations.CreateModel(
            name='DoctorClinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary clinic shown by default on doctor profile')),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Override consultation fee for this clinic. If null, uses doctor default fee.', max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_clinics', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_clinics', to='users.doctorprofile')),
            ],
            options={
                'db_table': 'doctor_clinics',
                'ordering': ['-is_primary', 'clinic__name'],
                'unique_together': {('doctor', 'clinic')},
            },
        ),
    ]
